In [2]:
import pandas as pd
import numpy as np
data = {
    'Name': ['Pandy', 'Bamboo', 'Fuzzy'],
    'Age': [5, 7, 4],
    'Bamboo_sticks' : [15, 6, 6]
}
df = pd.DataFrame(data)

In [3]:
print(df)

     Name  Age  Bamboo_sticks
0   Pandy    5             15
1  Bamboo    7              6
2   Fuzzy    4              6

In [4]:
df.head()

     Name  Age  Bamboo_sticks
0   Pandy    5             15
1  Bamboo    7              6
2   Fuzzy    4              6

In [5]:
df[df['Age']<6]   # df e filtering , filtering on a colums with a logic # df =df[df['Age']<6]

    Name  Age  Bamboo_sticks
0  Pandy    5             15
2  Fuzzy    4              6

In [6]:
df['Job'] = ['Intern', 'Manger', 'Intern']  #np.nan
print(df)

     Name  Age  Bamboo_sticks     Job
0   Pandy    5             15  Intern
1  Bamboo    7              6  Manger
2   Fuzzy    4              6  Intern

In [7]:
df.loc[df['Name']=='Pandy', 'Age'] = 6

In [8]:
df

     Name  Age  Bamboo_sticks     Job
0   Pandy    6             15  Intern
1  Bamboo    7              6  Manger
2   Fuzzy    4              6  Intern

In [9]:
df = df.drop('Bamboo_sticks', axis=1)

In [10]:
df

     Name  Age     Job
0   Pandy    6  Intern
1  Bamboo    7  Manger
2   Fuzzy    4  Intern