In [2]:
import pandas as pd
import numpy as np
data = {
    'Name': ['Pandy', 'Bamboo', 'Fuzzy'],
    'Age': [5, 7, 4],
    'Bamboo_sticks' : [15, 6, 6]
}
df = pd.DataFrame(data)

In [3]:
print(df)

     Name  Age  Bamboo_sticks
0   Pandy    5             15
1  Bamboo    7              6
2   Fuzzy    4              6

In [4]:
df.head()

     Name  Age  Bamboo_sticks
0   Pandy    5             15
1  Bamboo    7              6
2   Fuzzy    4              6

In [5]:
df[df['Age']<6]   # df e filtering , filtering on a colums with a logic # df =df[df['Age']<6]

    Name  Age  Bamboo_sticks
0  Pandy    5             15
2  Fuzzy    4              6

In [6]:
df['Job'] = ['Intern', 'Manger', 'Intern']  #np.nan
print(df)

     Name  Age  Bamboo_sticks     Job
0   Pandy    5             15  Intern
1  Bamboo    7              6  Manger
2   Fuzzy    4              6  Intern

In [7]:
df.loc[df['Name']=='Pandy', 'Age'] = 6

In [8]:
df

     Name  Age  Bamboo_sticks     Job
0   Pandy    6             15  Intern
1  Bamboo    7              6  Manger
2   Fuzzy    4              6  Intern

In [9]:
df = df.drop('Bamboo_sticks', axis=1)

In [10]:
df

     Name  Age     Job
0   Pandy    6  Intern
1  Bamboo    7  Manger
2   Fuzzy    4  Intern

In [11]:
df = df.drop(['Age','Job' ], axis=1)

In [12]:
df

     Name
0   Pandy
1  Bamboo
2   Fuzzy

In [13]:
df.iloc[:3] #row [0]

     Name
0   Pandy
1  Bamboo
2   Fuzzy

In [ ]:
df['Age']

In [ ]:
df.iloc[0:2, 0:2]

In [ ]:
df.iloc[0:2, 1:3]

In [ ]:
df = pd.DataFrame({
    'Name': ['Pandy', 'Bamboo', 'Fuzzy', 'Fluffy'],
    'Age': [5,7,4,6],
    'Bamboo_Stickes': [33,55,66,77]
},index = ['a','b','c','d'])

In [ ]:
df

In [ ]:
df.loc['b']

In [ ]:
df.loc[['a','c'], ['Name', 'Age']]

In [ ]:
df_json = pd.read_json('test.json' )

In [ ]:
df_json.head()

In [ ]:
df_json.tail()

In [ ]:
df_json.shape

In [ ]:
df_json.to_csv("Converted to csv.csv",index=False)

In [ ]:
df_csv = pd.read_csv("Converted to csv.csv")

In [ ]:
df_csv

In [ ]:
df_csv.drop('Calories',axis=1)

In [ ]:
df_csv

In [ ]:
df_csv.to_excel("output.xlsx",index=False)

In [ ]:
df_csv[['Duration', 'Pulse']]

In [ ]:
df_csv[(df_csv['Duration']>50) & (df_csv['Pulse']>105)]

In [ ]:
left = pd.DataFrame({
    'ID': [1,2,3],
    'Name' : ['Pandy', 'Fuzzy', 'Bamboo']
})
right = pd.DataFrame({
    'ID': [1,2,4],
    'hoby' : ['Climbing', 'Sleeping', 'Eating']
})
merge_df = pd.merge(left,right, on='ID', how='left')
print(merge_df)

In [ ]:
condatenated_df = pd.concat([left,right], ignore_index=True)
condatenated_df

In [ ]:
condatenated_df = pd.concat([left,right], axis=1)