In [119]:
import pandas as pd
import numpy as np
data = {
    'Name': ['Pandy', 'Bamboo', 'Fuzzy'],
    'Age': [5, 7, 4],
    'Bamboo_sticks' : [15, 6, 6]
}
df = pd.DataFrame(data)

In [120]:
print(df)

     Name  Age  Bamboo_sticks
0   Pandy    5             15
1  Bamboo    7              6
2   Fuzzy    4              6

In [121]:
df.head()

     Name  Age  Bamboo_sticks
0   Pandy    5             15
1  Bamboo    7              6
2   Fuzzy    4              6

In [122]:
df[df['Age']<6]   # df e filtering , filtering on a colums with a logic # df =df[df['Age']<6]

    Name  Age  Bamboo_sticks
0  Pandy    5             15
2  Fuzzy    4              6

In [123]:
df['Job'] = ['Intern', 'Manger', 'Intern']  #np.nan
print(df)

     Name  Age  Bamboo_sticks     Job
0   Pandy    5             15  Intern
1  Bamboo    7              6  Manger
2   Fuzzy    4              6  Intern

In [124]:
df.loc[df['Name']=='Pandy', 'Age'] = 6

In [125]:
df

     Name  Age  Bamboo_sticks     Job
0   Pandy    6             15  Intern
1  Bamboo    7              6  Manger
2   Fuzzy    4              6  Intern

In [126]:
df = df.drop('Bamboo_sticks', axis=1)

In [127]:
df

     Name  Age     Job
0   Pandy    6  Intern
1  Bamboo    7  Manger
2   Fuzzy    4  Intern

In [128]:
df = df.drop(['Age','Job' ], axis=1)

In [129]:
df

     Name
0   Pandy
1  Bamboo
2   Fuzzy

In [130]:
df.iloc[:3] #row [0]

     Name
0   Pandy
1  Bamboo
2   Fuzzy

In [131]:
df['Age']

KeyError: 'Age'

In [132]:
df.iloc[0:2, 0:2]

     Name
0   Pandy
1  Bamboo

In [133]:
df.iloc[0:2, 1:3]

Empty DataFrame
Columns: []
Index: [0, 1]