In [176]:
import pandas as pd
import numpy as np
data = {
    'Name': ['Pandy', 'Bamboo', 'Fuzzy'],
    'Age': [5, 7, 4],
    'Bamboo_sticks' : [15, 6, 6]
}
df = pd.DataFrame(data)

In [161]:
print(df)

     Name  Age  Bamboo_sticks
0   Pandy    5             15
1  Bamboo    7              6
2   Fuzzy    4              6

In [162]:
df.head()

     Name  Age  Bamboo_sticks
0   Pandy    5             15
1  Bamboo    7              6
2   Fuzzy    4              6

In [177]:
df[df['Age']<6]   # df e filtering , filtering on a colums with a logic # df =df[df['Age']<6]

    Name  Age  Bamboo_sticks
0  Pandy    5             15
2  Fuzzy    4              6

In [164]:
df['Job'] = ['Intern', 'Manger', 'Intern']  #np.nan
print(df)

     Name  Age  Bamboo_sticks     Job
0   Pandy    5             15  Intern
1  Bamboo    7              6  Manger
2   Fuzzy    4              6  Intern

In [165]:
df.loc[df['Name']=='Pandy', 'Age'] = 6

In [166]:
df

     Name  Age  Bamboo_sticks     Job
0   Pandy    6             15  Intern
1  Bamboo    7              6  Manger
2   Fuzzy    4              6  Intern

In [167]:
df = df.drop('Bamboo_sticks', axis=1)

In [168]:
df

     Name  Age     Job
0   Pandy    6  Intern
1  Bamboo    7  Manger
2   Fuzzy    4  Intern

In [169]:
df = df.drop(['Age','Job' ], axis=1)

In [170]:
df

     Name
0   Pandy
1  Bamboo
2   Fuzzy

In [171]:
df.iloc[:3] #row [0]

     Name
0   Pandy
1  Bamboo
2   Fuzzy

In [178]:
df['Age']

0    5
1    7
2    4
Name: Age, dtype: int64

In [ ]:
df.iloc[0:2, 0:2]

     Name
0   Pandy
1  Bamboo

In [ ]:
df.iloc[0:2, 1:3]

Empty DataFrame
Columns: []
Index: [0, 1]

In [ ]:
df = pd.DataFrame({
    'Name': ['Pandy', 'Bamboo', 'Fuzzy', 'Fluffy'],
    'Age': [5,7,4,6],
    'Bamboo_Stickes': [33,55,66,77]
},index = ['a','b','c','d'])

In [ ]:
df

     Name  Age  Bamboo_Stickes
a   Pandy    5              33
b  Bamboo    7              55
c   Fuzzy    4              66
d  Fluffy    6              77

In [ ]:
df.loc['b']

Name              Bamboo
Age                    7
Bamboo_Stickes        55
Name: b, dtype: object

In [ ]:
df.loc[['a','c'], ['Name', 'Age']]

    Name  Age
a  Pandy    5
c  Fuzzy    4

In [179]:
df_json = pd.read_json('test.json' )

In [ ]:
df_json.head()

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406

In [ ]:
df_json.tail()

   Duration  Pulse  Maxpulse  Calories
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300

In [181]:
df_json.shape

(6, 4)

In [180]:
df_json.to_csv("Converted to csv.csv",index=False)

In [182]:
df_csv = pd.read_csv("Converted to csv.csv")

In [ ]:
df_csv

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300

In [ ]:
df_csv.drop('Calories',axis=1)

   Duration  Pulse  Maxpulse
0        60    110       130
1        60    117       145
2        60    103       135
3        45    109       175
4        45    117       148
5        60    102       127

In [ ]:
df_csv

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300

In [183]:
df_csv.to_excel("output.xlsx", index=False)

In [ ]:
df_csv[['Duration', 'Pulse']]

   Duration  Pulse
0        60    110
1        60    117
2        60    103
3        45    109
4        45    117
5        60    102

In [ ]:
df_csv[(df_csv['Duration']>50) & (df_csv['Pulse']>105)]

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479

In [ ]:
left = pd.DataFrame({
    'ID': [1,2,3],
    'Name' : ['Pandy', 'Fuzzy', 'Bamboo']
})
right = pd.DataFrame({
    'ID': [1,2,4],
    'hoby' : ['Climbing', 'Sleeping', 'Eating']
})
merge_df = pd.merge(left,right, on='ID', how='left')
print(merge_df)

   ID    Name      hoby
0   1   Pandy  Climbing
1   2   Fuzzy  Sleeping
2   3  Bamboo       NaN

In [ ]:
condatenated_df = pd.concat([left,right], ignore_index=True)
condatenated_df

   ID    Name      hoby
0   1   Pandy       NaN
1   2   Fuzzy       NaN
2   3  Bamboo       NaN
3   1     NaN  Climbing
4   2     NaN  Sleeping
5   4     NaN    Eating

In [ ]:
condatenated_df = pd.concat([left,right], axis=1)

In [ ]:
condatenated_df

   ID    Name  ID      hoby
0   1   Pandy   1  Climbing
1   2   Fuzzy   2  Sleeping
2   3  Bamboo   4    Eating